#!/usr/bin/env python3
"""Build generated VIGIL aggregate and index files from individual records."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
VIGIL_DIR = ROOT / "vigil"
RECORDS_ROOT = VIGIL_DIR / "records"
OPEN_DIR = RECORDS_ROOT / "open"
CLUSTERS_DIR = RECORDS_ROOT / "clusters"
CLOSED_DIR = RECORDS_ROOT / "closed"
ACTIVE_RECORD_DIRS = [OPEN_DIR, CLUSTERS_DIR]
ALL_RECORD_DIRS = [OPEN_DIR, CLUSTERS_DIR, CLOSED_DIR]

ACTIVE_OUTPUT_PATH = VIGIL_DIR / "VIGIL.ActiveRecords.json"
CLOSED_OUTPUT_PATH = VIGIL_DIR / "VIGIL.ClosedRecords.json"
INDEX_OUTPUT_PATH = VIGIL_DIR / "VIGIL.Records.Index.json"

NOTICE = (
    "Generated by vigil/scripts/build-vigil-records.py; edit individual files "
    "under vigil/records/ instead."
)


def record_files(directories: list[Path]) -> list[Path]:
    files: list[Path] = []
    for directory in directories:
        if directory.exists():
            files.extend(directory.glob("*.json"))
    return sorted(files, key=lambda path: path.as_posix())


def load_records(directories: list[Path]) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in record_files(directories):
        with path.open("r", encoding="utf-8") as handle:
            record = json.load(handle)
        if not isinstance(record, dict):
            raise TypeError(f"{path} must contain one JSON object")
        records.append(record)
    return sorted(records, key=lambda record: record.get("id") or record.get("record_identity", {}).get("record_id", ""))


def aggregate(records: list[dict[str, Any]], generated_from: str) -> dict[str, Any]:
    return {
        "generated_notice": NOTICE,
        "generated_from": generated_from,
        "record_count": len(records),
        "records": records,
    }


def write_json(path: Path, data: Any) -> None:
    path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def record_path(record: dict[str, Any]) -> str:
    record_id = record.get("id", "")
    for path in record_files(ALL_RECORD_DIRS):
        if path.stem == record_id:
            return path.relative_to(ROOT).as_posix()
    return ""


def source_types(record: dict[str, Any]) -> list[str]:
    types = {
        source.get("source_type")
        for source in record.get("source_records", [])
        if isinstance(source, dict) and source.get("source_type")
    }
    source_data = record.get("source_data", {})
    if isinstance(source_data, dict) and source_data.get("source_type"):
        types.add(source_data["source_type"])
    return sorted(types)


def add_if_present(entry: dict[str, Any], record: dict[str, Any], field: str) -> None:
    if field in record:
        entry[field] = record.get(field)


def add_nested_if_present(
    entry: dict[str, Any], record: dict[str, Any], group: str, field: str, alias: str | None = None
) -> None:
    value = record.get(group, {})
    if isinstance(value, dict) and field in value:
        entry[alias or field] = value.get(field)


def index_record(record: dict[str, Any]) -> dict[str, Any]:
    record_identity = record.get("record_identity", {})
    failure_classification = record.get("failure_classification", {})
    linked_records = record.get("linked_records", {})
    cam_internal = record.get("cam_internal", {})
    entry: dict[str, Any] = {
        "id": record.get("id", ""),
        "record_type": record.get("record_type", ""),
        "legacy_record_type": record.get("legacy_record_type", ""),
        "status": record.get("status", ""),
        "date_recorded": record.get("date_recorded", ""),
        "record_identity": record_identity if isinstance(record_identity, dict) else {},
        "affected_domains": record.get("affected_domains", []),
        "affected_instruments": record.get("affected_instruments", []),
        "evidence_confidence": record.get("evidence_confidence", ""),
        "source_types": source_types(record),
        "failure_mode_ids": failure_classification.get("failure_mode_ids", []) if isinstance(failure_classification, dict) else [],
        "linked_records": linked_records if isinstance(linked_records, dict) else {},
        "cam_internal": cam_internal if isinstance(cam_internal, dict) else {},
    }
    for field in (
        "platform",
        "system_or_product",
        "model_or_algorithm",
        "deployment_context",
        "ecosystem_area",
        "failure_mode",
        "failure_family",
    ):
        add_if_present(entry, record, field)
    if "candidate_amendment_id" in record:
        entry["candidate_amendment_id"] = record.get("candidate_amendment_id")
    for group, field, alias in (
        ("source_data", "source_platform", "source_platform"),
        ("system_context", "platform_or_vendor", "platform_or_vendor"),
        ("system_context", "model_or_product", "model_or_product"),
        ("jurisdictional_context", "primary_jurisdiction", "primary_jurisdiction"),
        ("failure_classification", "severity", "severity"),
        ("failure_classification", "likelihood", "likelihood"),
    ):
        add_nested_if_present(entry, record, group, field, alias)
    entry["path"] = record_path(record)
    entry["summary"] = record.get("summary", "")
    return entry


def build() -> None:
    active_records = load_records(ACTIVE_RECORD_DIRS)
    closed_records = load_records([CLOSED_DIR])
    all_records = sorted(
        [*active_records, *closed_records], key=lambda record: record.get("id", "")
    )
    index_records = [index_record(record) for record in all_records]

    write_json(
        ACTIVE_OUTPUT_PATH,
        aggregate(active_records, "vigil/records/open/ and vigil/records/clusters/"),
    )
    write_json(CLOSED_OUTPUT_PATH, aggregate(closed_records, "vigil/records/closed/"))
    write_json(
        INDEX_OUTPUT_PATH,
        {
            "generated_notice": NOTICE,
            "generated_from": "vigil/records/",
            "record_count": len(index_records),
            "records": index_records,
        },
    )
    print(f"Wrote {ACTIVE_OUTPUT_PATH} with {len(active_records)} records.")
    print(f"Wrote {CLOSED_OUTPUT_PATH} with {len(closed_records)} records.")
    print(f"Wrote {INDEX_OUTPUT_PATH} with {len(index_records)} records.")


if __name__ == "__main__":
    build()
