#!/usr/bin/env python3
"""Build the VIGIL LEARN index and add LEARN records to the generated master registry."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
VIGIL_DIR = ROOT / "vigil"
LEARN_ROOT = VIGIL_DIR / "records" / "learn"
LEARN_INDEX = VIGIL_DIR / "VIGIL.Learn.Index.json"
MASTER_INDEX = VIGIL_DIR / "VIGIL.Registry.Index.json"
REPOSITORY = "CAM-Initiative/Vigil"
DEFAULT_BRANCH = "main"
NOTICE = (
    "Generated by vigil/scripts/build-vigil-learn-records.py from individual LEARN records under "
    "vigil/records/learn/<year>/; edit source records only."
)
GENERATED_PROVENANCE = {
    "content_origin": "deterministically-generated",
    "generation_mode": "deterministic-generation",
    "human_role": "contract-approver",
    "human_authorship": False,
    "human_review_status": "not-reviewed",
    "human_verification_status": "not-verified",
    "declaration": "vigil/provenance/AUTHORSHIP-PROVENANCE.json",
}


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, value: Any) -> None:
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def repo_relative_path(path: Path) -> str:
    return path.resolve().relative_to(ROOT.resolve()).as_posix()


def github_blob_url(path: str) -> str:
    return f"https://github.com/{REPOSITORY}/blob/{DEFAULT_BRANCH}/{path}"


def raw_url(path: str) -> str:
    return f"https://raw.githubusercontent.com/{REPOSITORY}/{DEFAULT_BRANCH}/{path}"


def learn_files() -> list[Path]:
    return sorted(LEARN_ROOT.rglob("*.json"), key=lambda item: item.as_posix()) if LEARN_ROOT.exists() else []


def load_learn_records() -> list[tuple[Path, dict[str, Any]]]:
    records: list[tuple[Path, dict[str, Any]]] = []
    for path in learn_files():
        record = load_json(path)
        if not isinstance(record, dict):
            raise TypeError(f"{path} must contain one JSON object")
        if record.get("record_type") != "learn":
            raise ValueError(f"{path} is not a LEARN record")
        records.append((path, record))
    return records


def index_entry(path: Path, record: dict[str, Any]) -> dict[str, Any]:
    relative = repo_relative_path(path)
    identity = record.get("record_identity") if isinstance(record.get("record_identity"), dict) else {}
    case_context = record.get("case_context") if isinstance(record.get("case_context"), dict) else {}
    linked = record.get("linked_records") if isinstance(record.get("linked_records"), dict) else {}
    completion = record.get("chain_completion") if isinstance(record.get("chain_completion"), dict) else {}
    taxonomy_links = record.get("failure_taxonomy_links") if isinstance(record.get("failure_taxonomy_links"), list) else []
    primary_taxonomy = taxonomy_links[0] if taxonomy_links and isinstance(taxonomy_links[0], dict) else {}

    return {
        "id": record.get("id", ""),
        "record_type": "learn",
        "record_state": record.get("record_state", ""),
        "date_recorded": record.get("date_recorded", ""),
        "title": identity.get("title") or record.get("report_title", ""),
        "report_title": record.get("report_title", ""),
        "case_descriptor": record.get("case_descriptor", ""),
        "summary": record.get("summary", ""),
        "what_happened": record.get("what_happened", []),
        "governance_misconception": record.get("governance_misconception", []),
        "abstracted_learning": record.get("abstracted_learning", ""),
        "integrated_learning": record.get("integrated_learning", []),
        "risk_if_not_integrated": record.get("risk_if_not_integrated", []),
        "future_application": record.get("future_application", []),
        "generalisation_boundary": record.get("generalisation_boundary", ""),
        "knowledge_status": record.get("knowledge_status", ""),
        "publication_status": record.get("publication_status", ""),
        "knowledge_tags": record.get("knowledge_tags", []),
        "year": case_context.get("year", ""),
        "first_occurrence_date": case_context.get("first_occurrence_date", ""),
        "first_occurrence_basis": case_context.get("first_occurrence_basis", ""),
        "primary_vendors": case_context.get("primary_vendors", []),
        "incident_status": case_context.get("incident_status", ""),
        "cam_repair_status": case_context.get("cam_repair_status", ""),
        "monitoring_required": case_context.get("monitoring_required", False),
        "chain_state": completion.get("overall_status", ""),
        "primary_failure_mode": record.get("learning_basis", {}).get("primary_failure_mode", "")
        if isinstance(record.get("learning_basis"), dict)
        else "",
        "primary_failure_family_code": primary_taxonomy.get("primary_failure_family_code", ""),
        "canonical_failure_name": primary_taxonomy.get("canonical_failure_name", ""),
        "taxonomy_reference": primary_taxonomy.get("taxonomy_reference", ""),
        "taxonomy_status": primary_taxonomy.get("taxonomy_status", ""),
        "establishing_patch_id": primary_taxonomy.get("establishing_patch_id", ""),
        "related_observations": linked.get("related_observations", []),
        "related_failure_modes": linked.get("related_failure_modes", []),
        "related_proposals": linked.get("related_proposals", []),
        "related_patch_notes": linked.get("related_patch_notes", []),
        "related_learn_records": linked.get("related_learn_records", []),
        "path": relative,
        "github_blob_url": github_blob_url(relative),
        "raw_url": raw_url(relative),
    }


def build_learn_index(records: list[tuple[Path, dict[str, Any]]]) -> dict[str, Any]:
    return {
        "generated_notice": NOTICE,
        "authorship_provenance": {
            **GENERATED_PROVENANCE,
            "upstream_provenance": ["vigil/records/learn/"],
        },
        "registry_type": "learn_records",
        "generated_from": "vigil/records/learn/",
        "record_count": len(records),
        "records": [index_entry(path, record) for path, record in records],
    }


def augment_master(learn_index: dict[str, Any]) -> None:
    if not MASTER_INDEX.exists() or not MASTER_INDEX.read_text(encoding="utf-8").strip():
        raise RuntimeError(
            "VIGIL.Registry.Index.json must be generated by build-vigil-records.py before LEARN augmentation"
        )
    master = load_json(MASTER_INDEX)
    if not isinstance(master, dict):
        raise TypeError("VIGIL.Registry.Index.json must contain one JSON object")

    learn_records = [record for record in learn_index.get("records", []) if isinstance(record, dict)]
    master_records = [
        record
        for record in master.get("records", [])
        if isinstance(record, dict) and record.get("record_type") != "learn"
    ]
    master["records"] = sorted(
        [*master_records, *learn_records], key=lambda record: str(record.get("id", ""))
    )

    relative_index = repo_relative_path(LEARN_INDEX)
    registries = master.get("registries")
    if not isinstance(registries, dict):
        registries = {}
        master["registries"] = registries
    registries["learn_records"] = {
        "path": relative_index,
        "github_blob_url": github_blob_url(relative_index),
        "raw_url": raw_url(relative_index),
        "record_count": len(learn_records),
    }
    master["registry_count"] = len(registries)

    counts = master.get("record_count")
    if not isinstance(counts, dict):
        counts = {}
        master["record_count"] = counts
    counts["learn_records"] = len(learn_records)
    counts["total"] = sum(
        value
        for key, value in counts.items()
        if key != "total" and isinstance(value, int)
    )

    generated_from = master.get("generated_from")
    if not isinstance(generated_from, list):
        generated_from = []
        master["generated_from"] = generated_from
    if relative_index not in generated_from:
        generated_from.append(relative_index)

    provenance = master.get("authorship_provenance")
    if isinstance(provenance, dict):
        upstream = provenance.get("upstream_provenance")
        if not isinstance(upstream, list):
            upstream = []
            provenance["upstream_provenance"] = upstream
        if relative_index not in upstream:
            upstream.append(relative_index)

    write_json(MASTER_INDEX, master)


def main() -> int:
    records = load_learn_records()
    index = build_learn_index(records)
    write_json(LEARN_INDEX, index)
    augment_master(index)
    print(f"Wrote {LEARN_INDEX} with {len(records)} LEARN record(s).")
    print(f"Augmented {MASTER_INDEX} with LEARN registry metadata and records.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
