#!/usr/bin/env python3
"""Build generated VIGIL aggregate and index files from individual records."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
VIGIL_DIR = ROOT / "vigil"
RECORDS_ROOT = VIGIL_DIR / "records"
RECORD_TYPE_DIRS = [
    RECORDS_ROOT / "observations",
    RECORDS_ROOT / "failures",
    RECORDS_ROOT / "proposals",
    RECORDS_ROOT / "patches",
    RECORDS_ROOT / "research",
]
CLOSED_STATES = {"closed-no-action", "closed-actioned", "completed"}
ACTIVE_STATES = {"watching", "active", "open", "routed", "deferred", "clustered", "in-drafting", "under-review"}
TYPE_DIR = {
    "observation": "observations",
    "failure_mode": "failures",
    "proposal": "proposals",
    "patch": "patches",
    "research": "research",
}
ACTIVE_OUTPUT_PATH = VIGIL_DIR / "VIGIL.ActiveRecords.json"
CLOSED_OUTPUT_PATH = VIGIL_DIR / "VIGIL.ClosedRecords.json"
INDEX_OUTPUT_PATH = VIGIL_DIR / "VIGIL.Records.Index.json"
NOTICE = "Generated by vigil/scripts/build-vigil-records.py from individual records under vigil/records/<record_type>/<year>/; edit source records only."


def record_files(directories: list[Path] | None = None) -> list[Path]:
    """Return individual record JSON files under canonical type/year folders."""
    files: list[Path] = []
    for directory in directories or RECORD_TYPE_DIRS:
        if directory.exists():
            files.extend(directory.rglob("*.json"))
    return sorted(files, key=lambda path: path.as_posix())


def contains_key(value: Any, key: str) -> bool:
    if isinstance(value, dict):
        return key in value or any(contains_key(item, key) for item in value.values())
    if isinstance(value, list):
        return any(contains_key(item, key) for item in value)
    return False


def load_records(directories: list[Path] | None = None) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in record_files(directories):
        with path.open("r", encoding="utf-8") as handle:
            record = json.load(handle)
        if not isinstance(record, dict):
            raise TypeError(f"{path} must contain one JSON object")
        if contains_key(record, "source_data"):
            raise ValueError(f"{path} contains forbidden source_data")
        records.append(record)
    return sorted(records, key=lambda record: record.get("id", ""))


def prune_empty(value: Any) -> Any:
    """Recursively remove empty generated-output values while preserving uncertainty text."""
    if isinstance(value, dict):
        pruned = {key: prune_empty(item) for key, item in value.items()}
        return {key: item for key, item in pruned.items() if item not in (None, "", [], {})}
    if isinstance(value, list):
        pruned_items = [prune_empty(item) for item in value]
        return [item for item in pruned_items if item not in (None, "", [], {})]
    return value


def dict_summary(
    record: dict[str, Any], field: str, keys: list[str] | None = None
) -> dict[str, Any]:
    section = record.get(field)
    if not isinstance(section, dict):
        return {}
    if keys is None:
        return dict(section)
    return {key: section.get(key, "") for key in keys}


def system_summary(record: dict[str, Any]) -> dict[str, Any]:
    return dict_summary(
        record,
        "system_context",
        [
            "system_type",
            "platform_or_vendor",
            "product_family",
            "product_or_service",
            "model_or_product",
            "specific_model",
            "interaction_mode",
            "interface_surface",
            "embodiment_status",
            "deployment_context",
            "user_role",
            "affected_population",
        ],
    )


def pick_keys(section: dict[str, Any], keys: list[str]) -> dict[str, Any]:
    return {key: section.get(key, "") for key in keys}


def jurisdiction_summary(record: dict[str, Any]) -> dict[str, Any]:
    return dict_summary(
        record,
        "jurisdictional_context",
        [
            "primary_jurisdiction",
            "secondary_jurisdictions",
            "regulatory_surface",
            "sector",
            "cross_border_relevance",
            "public_interest_relevance",
        ],
    )


def possible_taxonomy_mapping_summary(record: dict[str, Any]) -> dict[str, Any]:
    return dict_summary(record, "possible_taxonomy_mapping")


def classification_summary(record: dict[str, Any]) -> dict[str, Any]:
    return dict_summary(
        record,
        "failure_classification",
        [
            "canonical_failure_group",
            "failure_family",
            "failure_subtype",
            "taxonomy_reference",
            "related_failure_groups",
            "harm_vectors",
            "severity",
            "likelihood",
            "confidence",
            "affected_rights_or_interests",
            "failure_scope",
            "recurrence_pattern",
            "persistence",
            "reproducibility",
            "visibility",
        ],
    )


def triage_summary(record: dict[str, Any]) -> dict[str, Any]:
    return dict_summary(
        record,
        "triage",
        [
            "triage_priority",
            "triage_status",
            "mitigation_status",
            "escalation_required",
            "recommended_next_step",
        ],
    )


def proposal_summary(record: dict[str, Any]) -> dict[str, Any]:
    proposal_scope = record.get("proposal_scope")
    scope = proposal_scope if isinstance(proposal_scope, dict) else {}
    return {
        "proposal_type": record.get("proposal_type", []),
        "scope_summary": scope.get("scope_summary", ""),
        "cam_domains": scope.get("cam_domains", []),
        "registry_components": scope.get("registry_components", []),
        "automation_components": scope.get("automation_components", []),
        "interface_components": scope.get("interface_components", []),
        "next_action": record.get("next_action", ""),
    }


def external_relevance_summary(record: dict[str, Any]) -> dict[str, Any]:
    return dict_summary(record, "external_relevance")


def change_summary(record: dict[str, Any]) -> dict[str, Any]:
    classification = record.get("change_classification")
    change_classification = classification if isinstance(classification, dict) else {}
    details = record.get("change_details")
    change_details = details if isinstance(details, dict) else {}
    return {
        "patch_type": change_classification.get("patch_type") or change_classification.get("change_type", []),
        "change_scope": change_classification.get("change_scope", ""),
        "implementation_mode": change_classification.get("implementation_mode")
        or change_classification.get("implementation_status", ""),
        "date_implemented": record.get("date_implemented", ""),
        "files_changed": change_details.get("files_changed")
        or change_details.get("changed_files_or_instruments", []),
        "records_changed": change_details.get("records_changed", []),
        "schemas_changed": change_details.get("schemas_changed", []),
        "templates_changed": change_details.get("templates_changed", []),
        "scripts_changed": change_details.get("scripts_changed", []),
        "workflows_changed": change_details.get("workflows_changed", []),
        "interface_components_changed": change_details.get("interface_components_changed", []),
    }


def verification_summary(record: dict[str, Any]) -> dict[str, Any]:
    return dict_summary(record, "implementation_verification")


def impact_summary(record: dict[str, Any]) -> dict[str, Any]:
    return dict_summary(record, "impact_summary")


def proposal_cam_summary(record: dict[str, Any]) -> dict[str, Any]:
    cam = record.get("cam_internal")
    if not isinstance(cam, dict):
        return {}
    return pick_keys(
        cam,
        [
            "target_instruments",
            "target_annexes",
            "target_domains",
            "governance_layer",
            "drafting_status",
            "validator_or_automation_impact",
            "interface_impact",
            "registry_impact",
        ],
    )


def patch_cam_summary(record: dict[str, Any]) -> dict[str, Any]:
    cam = record.get("cam_internal")
    if not isinstance(cam, dict):
        return {}
    return pick_keys(
        cam,
        [
            "changed_instruments",
            "changed_annexes",
            "changed_domains",
            "changed_registry_components",
            "changed_templates",
            "changed_schemas",
            "changed_validators",
            "changed_automations",
            "changed_interface_components",
            "governance_layer",
        ],
    )


def generated_summaries(record: dict[str, Any]) -> dict[str, Any]:
    record_type = record.get("record_type", "")
    summaries: dict[str, Any] = {"source_summary": source_summary(record)}

    if record_type == "observation":
        summaries.update(
            {
                "system_summary": system_summary(record),
                "jurisdiction_summary": jurisdiction_summary(record),
                "possible_taxonomy_mapping_summary": possible_taxonomy_mapping_summary(record),
            }
        )
    elif record_type == "failure_mode":
        summaries.update(
            {
                "system_summary": system_summary(record),
                "jurisdiction_summary": jurisdiction_summary(record),
                "classification_summary": classification_summary(record),
                "triage_summary": triage_summary(record),
            }
        )
    elif record_type == "proposal":
        summaries.update(
            {
                "system_summary": system_summary(record),
                "proposal_summary": proposal_summary(record),
                "external_relevance_summary": external_relevance_summary(record),
                "cam_summary": proposal_cam_summary(record),
            }
        )
    elif record_type in {"patch", "patch_note"}:
        summaries.update(
            {
                "system_summary": system_summary(record),
                "change_summary": change_summary(record),
                "verification_summary": verification_summary(record),
                "impact_summary": impact_summary(record),
                "cam_summary": patch_cam_summary(record),
            }
        )

    return prune_empty(summaries)


def write_json(path: Path, data: Any) -> None:
    pruned = prune_empty(data)
    if isinstance(data, dict) and "records" in data and isinstance(pruned, dict):
        pruned.setdefault("records", [])
    path.write_text(json.dumps(pruned, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def canonical_sources(record: dict[str, Any]) -> list[dict[str, Any]]:
    sources = record.get("source_records", [])
    return [source for source in sources if isinstance(source, dict)] if isinstance(sources, list) else []


def source_summary(record: dict[str, Any]) -> dict[str, Any]:
    sources = canonical_sources(record)
    primary = sources[0] if sources else {}
    return {
        "primary_source_title": primary.get("source_title") or primary.get("title", ""),
        "primary_source_type": primary.get("source_type", ""),
        "primary_source_url": primary.get("source_url") or primary.get("url", ""),
        "primary_archive_url": primary.get("archive_url", ""),
        "primary_source_platform": primary.get("source_platform") or primary.get("platform", ""),
        "primary_source_author_or_publisher": primary.get("author_or_publisher", ""),
        "source_count": len(sources),
        "source_url_status": primary.get("source_url_status", ""),
        "evidence_confidence": record.get("evidence_confidence", ""),
    }


def source_types(record: dict[str, Any]) -> list[str]:
    return sorted({source.get("source_type") for source in canonical_sources(record) if source.get("source_type")})


def record_path(record: dict[str, Any]) -> str:
    record_id = record.get("id", "")
    for path in record_files():
        if path.stem == record_id:
            try:
                return path.relative_to(ROOT).as_posix()
            except ValueError:
                return path.as_posix()
    return ""


def aggregate_record(record: dict[str, Any]) -> dict[str, Any]:
    entry = dict(record)
    entry.update(generated_summaries(record))
    return entry


def index_record(record: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": record.get("id", ""),
        "record_type": record.get("record_type", ""),
        "record_state": record.get("record_state", ""),
        "date_recorded": record.get("date_recorded", ""),
        "record_identity": record.get("record_identity", {}) if isinstance(record.get("record_identity"), dict) else {},
        "summary": record.get("summary", ""),
        "evidence_confidence": record.get("evidence_confidence", ""),
        "source_types": source_types(record),
        **generated_summaries(record),
        "linked_records": record.get("linked_records", {}) if isinstance(record.get("linked_records"), dict) else {},
        "path": record_path(record),
    }


def aggregate(records: list[dict[str, Any]], generated_from: str) -> dict[str, Any]:
    return {
        "generated_notice": NOTICE,
        "generated_from": generated_from,
        "record_count": len(records),
        "records": [aggregate_record(record) for record in records],
    }


def is_closed_record(record: dict[str, Any]) -> bool:
    state = str(record.get("record_state", "")).lower()
    return state in CLOSED_STATES or (state == "implemented" and record.get("record_type") == "patch")


def is_active_record(record: dict[str, Any]) -> bool:
    return str(record.get("record_state", "")).lower() in ACTIVE_STATES


def generated_from_for(records: list[dict[str, Any]]) -> str:
    roots = sorted({
        f"vigil/records/{TYPE_DIR.get(str(record.get('record_type', '')), str(record.get('record_type', 'unknown')))}/{str(record.get('id', '')).split('-')[1] if len(str(record.get('id', '')).split('-')) > 1 else 'unknown'}/"
        for record in records
    })
    return ", ".join(roots) if roots else "vigil/records/<record_type>/<year>/"


def build() -> None:
    all_records = load_records()
    active_records = [record for record in all_records if is_active_record(record)]
    closed_records = [record for record in all_records if is_closed_record(record)]
    write_json(ACTIVE_OUTPUT_PATH, aggregate(active_records, generated_from_for(active_records)))
    write_json(CLOSED_OUTPUT_PATH, aggregate(closed_records, generated_from_for(closed_records)))
    write_json(
        INDEX_OUTPUT_PATH,
        {
            "generated_notice": NOTICE,
            "generated_from": "vigil/records/",
            "record_count": len(all_records),
            "records": [index_record(record) for record in all_records],
        },
    )
    print(f"Wrote {ACTIVE_OUTPUT_PATH} with {len(active_records)} records.")
    print(f"Wrote {CLOSED_OUTPUT_PATH} with {len(closed_records)} records.")
    print(f"Wrote {INDEX_OUTPUT_PATH} with {len(all_records)} records.")


if __name__ == "__main__":
    build()
