#!/usr/bin/env python3
"""Build the Incident-only public VIGIL indexes from canonical Incident records."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
VIGIL = ROOT / "vigil"
INCIDENTS = VIGIL / "records" / "incidents"
INCIDENT_INDEX = VIGIL / "VIGIL.Incidents.Index.json"
MASTER_INDEX = VIGIL / "VIGIL.Registry.Index.json"
TAXONOMY_EXAMPLES = VIGIL / "taxonomy" / "generated" / "VIGIL.FailureTaxonomy.CaseFileExamples.json"
TAXONOMY_INDEX = VIGIL / "taxonomy" / "VIGIL.FailureTaxonomy.Index.json"
REPOSITORY = "CAM-Initiative/Vigil"
BRANCH = "main"
NOTICE = (
    "Generated by vigil/scripts/build-vigil-public-records.py from canonical Incident "
    "records under vigil/records/incidents/; edit source records only."
)
GENERATED_PROVENANCE = {
    "content_origin": "deterministically-generated",
    "generation_mode": "deterministic-generation",
    "human_role": "contract-approver",
    "human_authorship": False,
    "human_review_status": "not-reviewed",
    "human_verification_status": "not-verified",
}
PRESERVE_EMPTY_KEYS = {
    "legacy_sources", "legacy_provenance", "secondary_classifications",
    "external_incident_references",
}


def load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected one JSON object")
    return value


def prune(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            key: cleaned
            for key, item in value.items()
            if (cleaned := prune(item)) not in (None, "", [], {}) or key in PRESERVE_EMPTY_KEYS
        }
    if isinstance(value, list):
        return [cleaned for item in value if (cleaned := prune(item)) not in (None, "", [], {})]
    return value


def write(path: Path, value: Any) -> None:
    path.write_text(
        json.dumps(prune(value), indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def relative(path: Path) -> str:
    return path.resolve().relative_to(ROOT.resolve()).as_posix()


def github_url(path: str) -> str:
    return f"https://github.com/{REPOSITORY}/blob/{BRANCH}/{path}"


def raw_url(path: str) -> str:
    return f"https://raw.githubusercontent.com/{REPOSITORY}/{BRANCH}/{path}"


def sources(record: dict[str, Any]) -> list[dict[str, Any]]:
    value = record.get("source_records")
    return [item for item in value if isinstance(item, dict)] if isinstance(value, list) else []


def evidence_statuses(record: dict[str, Any]) -> list[str]:
    return sorted(
        {str(item["evidence_status"]) for item in sources(record) if item.get("evidence_status")}
    )


def preferred_evidence_status(record: dict[str, Any]) -> str:
    preferred = record.get("preferred_evidence")
    if not isinstance(preferred, dict):
        return ""
    matches = [
        item.get("evidence_status", "")
        for item in sources(record)
        if item.get("source_url") == preferred.get("source_url")
    ]
    return str(matches[0]) if len(matches) == 1 else ""


def severity_assessment_basis(record: dict[str, Any]) -> str:
    """Derive temporary compatibility prose from canonical structured analysis."""
    assessment = record.get("severity_assessment")
    if not isinstance(assessment, dict):
        return ""
    severity = str(assessment.get("severity", ""))
    if severity == "SU":
        gap = assessment.get("assessment_gap")
        return f"SU: {gap}" if isinstance(gap, str) and gap.strip() else ""
    labels = (
        ("Materialised consequence", "materialised_consequence"),
        ("Affected scope", "affected_scope"),
        ("Seriousness and persistence", "seriousness_and_persistence"),
        ("Quantitative information", "quantitative_information"),
        ("Evidentiary limits", "evidentiary_limits"),
        ("Band rationale", "band_rationale"),
    )
    parts = [
        f"{label}: {assessment[field]}"
        for label, field in labels
        if isinstance(assessment.get(field), str) and assessment[field].strip()
    ]
    return f"{severity}: " + " ".join(parts) if parts else ""


def review_summary(record: dict[str, Any]) -> dict[str, Any]:
    provenance = record.get("interpretive_provenance")
    if not isinstance(provenance, dict):
        return {}
    current = provenance.get("current_ai_review")
    editor = provenance.get("human_governance_editor")
    output: dict[str, Any] = {
        "operating_model": "AI-authored, semi-autonomous production under human contract approval",
        "review_count": len(provenance.get("review_history", []))
        if isinstance(provenance.get("review_history"), list)
        else 0,
    }
    if isinstance(current, dict):
        output["ai_reviewer"] = {
            "platform": current.get("reviewer_platform"),
            "model": current.get("reviewer_model"),
            "review_date": current.get("review_date"),
            "review_scope": current.get("review_scope"),
            "capability_profile": current.get("capability_profile"),
            "known_limitations": current.get("known_limitations"),
        }
    if isinstance(editor, dict):
        output["human_contract_approver"] = {
            "name": editor.get("name"),
            "role": "contract-approver",
            "human_authorship": False,
            "human_review_status": "not-reviewed",
            "human_verification_status": "not-verified",
        }
    return prune(output)

def evidence_access_summary(record: dict[str, Any]) -> dict[str, Any]:
    modalities: list[str] = []
    states: list[str] = []
    direct = 0
    indirect = 0
    for item in sources(record):
        values = item.get("evidence_modality")
        if isinstance(values, list):
            modalities.extend(str(value) for value in values)
        access = item.get("primary_artefact_access")
        if not isinstance(access, dict):
            continue
        if access.get("access_status"):
            states.append(str(access["access_status"]))
        if access.get("direct_primary_artefact_review") is True:
            direct += 1
        elif access.get("direct_primary_artefact_review") is False:
            indirect += 1
    return {
        "evidence_modalities": sorted(set(modalities)),
        "primary_artefact_access_states": sorted(set(states)),
        "direct_primary_artefact_reviews": direct,
        "indirect_or_unavailable_primary_artefact_reviews": indirect,
    }


def incident_entry(path: Path, record: dict[str, Any]) -> dict[str, Any]:
    identity = record.get("record_identity") if isinstance(record.get("record_identity"), dict) else {}
    incident = record.get("incident_identity") if isinstance(record.get("incident_identity"), dict) else {}
    system = record.get("system_context") if isinstance(record.get("system_context"), dict) else {}
    jurisdiction = record.get("jurisdictional_context") if isinstance(record.get("jurisdictional_context"), dict) else {}
    taxonomy = record.get("taxonomy_classification") if isinstance(record.get("taxonomy_classification"), dict) else {}
    preferred = record.get("preferred_evidence") if isinstance(record.get("preferred_evidence"), dict) else {}
    assessment = record.get("severity_assessment") if isinstance(record.get("severity_assessment"), dict) else {}
    source_list = sources(record)
    primary = source_list[0] if source_list else {}
    diagnostic = record.get("diagnostic_provenance")
    diagnostic_summary = (
        {
            key: diagnostic.get(key)
            for key in (
                "method", "diagnostic_date", "human_role", "ai_role", "ai_platform", "ai_model",
                "model_attribution_basis", "review_status", "authority_boundary",
                "date_attribution_status", "date_anomaly_note",
            )
            if diagnostic.get(key) not in (None, "", [], {})
        }
        if isinstance(diagnostic, dict)
        else {}
    )
    record_path = relative(path)
    return prune({
        "id": record.get("id"), "record_type": record.get("record_type"),
        "record_state": record.get("record_state"), "date_recorded": record.get("date_recorded"),
        "title": identity.get("title") or record.get("summary") or record.get("id"),
        "summary": record.get("summary"), "source_count": len(source_list),
        "primary_source_title": primary.get("source_title"),
        "primary_source_type": primary.get("source_type"),
        "primary_source_platform": primary.get("source_platform"),
        "source_platforms": sorted({item.get("source_platform") for item in source_list if item.get("source_platform")}),
        "source_types": sorted({item.get("source_type") for item in source_list if item.get("source_type")}),
        "source_url_status": primary.get("source_url_status"),
        "system_type": system.get("system_type"), "platform_or_vendor": system.get("platform_or_vendor"),
        "vendor_cluster": system.get("vendor_cluster"), "primary_evidenced_vendors": system.get("primary_evidenced_vendors"),
        "evidence_scope": system.get("evidence_scope"), "evidenced_vendors": system.get("evidenced_vendors"),
        "evidenced_products_or_services": system.get("evidenced_products_or_services"),
        "evidenced_models_or_runtimes": system.get("evidenced_models_or_runtimes"),
        "product_or_service": system.get("product_or_service"),
        "specific_model_or_runtime": system.get("specific_model_or_runtime"),
        "model_or_product": system.get("model_or_product"), "interface_surface": system.get("interface_surface"),
        "deployment_context": system.get("deployment_context"),
        "primary_jurisdiction": jurisdiction.get("primary_jurisdiction"),
        "regulatory_surface": jurisdiction.get("regulatory_surface"), "sector": jurisdiction.get("sector"),
        "severity": assessment.get("severity"), "severity_assessment": assessment,
        "severity_assessment_status": assessment.get("assessment_status"),
        "severity_assessment_basis": severity_assessment_basis(record),
        "classification_status": taxonomy.get("classification_status"),
        "primary_classification": taxonomy.get("primary_classification"),
        "secondary_classifications": taxonomy.get("secondary_classifications"),
        "occurred_from": incident.get("occurred_from"), "occurred_to": incident.get("occurred_to"),
        "date_precision": incident.get("date_precision"), "preferred_evidence_url": preferred.get("source_url"),
        "evidence_statuses": evidence_statuses(record),
        "preferred_evidence_status": preferred_evidence_status(record),
        "external_incident_references": record.get("external_incident_references"),
        "legacy_provenance": record.get("legacy_provenance"),
        "diagnostic_provenance_summary": diagnostic_summary,
        "interpretive_provenance_summary": review_summary(record),
        "evidence_access_summary": evidence_access_summary(record),
        "path": record_path, "github_blob_url": github_url(record_path), "raw_url": raw_url(record_path),
    })


def taxonomy_examples(records: list[dict[str, Any]]) -> dict[str, Any]:
    taxonomy = load(TAXONOMY_INDEX)
    classes: dict[str, list[dict[str, Any]]] = {}
    for family in taxonomy.get("families", []):
        if not isinstance(family, dict) or not isinstance(family.get("file"), str):
            continue
        document = load(TAXONOMY_INDEX.parent / family["file"])
        for item in document.get("classes", []):
            if isinstance(item, dict) and isinstance(item.get("class_id"), str):
                classes[item["class_id"]] = []
    for record in records:
        block = record.get("taxonomy_classification")
        if not isinstance(block, dict):
            continue
        mappings: list[tuple[str, dict[str, Any]]] = []
        primary = block.get("primary_classification")
        if isinstance(primary, dict):
            mappings.append(("primary", primary))
        secondary = block.get("secondary_classifications")
        if isinstance(secondary, list):
            mappings.extend(("secondary", item) for item in secondary if isinstance(item, dict))
        for role, mapping in mappings:
            class_id = mapping.get("class_id")
            if class_id not in classes:
                continue
            classes[class_id].append(prune({
                "incident_id": record.get("id"),
                "incident_title": record.get("record_identity", {}).get("title"),
                "classification_role": role,
                "classification_basis": mapping.get("classification_basis"),
                "classification_confidence": mapping.get("classification_confidence"),
            }))
    return {
        "generated_notice": NOTICE, "generated_from": "vigil/records/incidents/",
        "authorship_provenance": {
            **GENERATED_PROVENANCE,
            "upstream_provenance": ["vigil/records/incidents/", relative(TAXONOMY_INDEX)],
        },
        "classes": classes,
    }


def build() -> None:
    paths = sorted(INCIDENTS.glob("VIGIL-INC-*.json"), key=lambda item: item.name)
    records = [load(path) for path in paths]
    entries = [incident_entry(path, record) for path, record in zip(paths, records)]
    provenance = {**GENERATED_PROVENANCE, "upstream_provenance": ["vigil/records/incidents/"]}
    incident_index = {
        "registry_type": "incidents", "generated_notice": NOTICE,
        "generated_from": "vigil/records/incidents/", "authorship_provenance": provenance,
        "record_count": len(entries), "records": entries,
    }
    index_path = relative(INCIDENT_INDEX)
    master = {
        "registry_type": "vigil_registry_master", "generated_notice": NOTICE,
        "generated_from": [index_path],
        "authorship_provenance": {**GENERATED_PROVENANCE, "upstream_provenance": [index_path]},
        "registry_count": 1, "record_count": {"incidents": len(entries), "total": len(entries)},
        "registries": {"incidents": {
            "path": index_path, "github_blob_url": github_url(index_path),
            "raw_url": raw_url(index_path), "record_count": len(entries),
        }},
        "records": entries,
    }
    write(INCIDENT_INDEX, incident_index)
    write(MASTER_INDEX, master)
    write(TAXONOMY_EXAMPLES, taxonomy_examples(records))
    print(f"Wrote Incident-only VIGIL indexes for {len(entries)} canonical records.")


if __name__ == "__main__":
    build()
