#!/usr/bin/env python3
"""Build the Incident-only public VIGIL indexes from canonical Incident records."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
VIGIL = ROOT / "vigil"
INCIDENTS = VIGIL / "records" / "incidents"
INCIDENT_INDEX = VIGIL / "VIGIL.Incidents.Index.json"
MASTER_INDEX = VIGIL / "VIGIL.Registry.Index.json"
TAXONOMY_EXAMPLES = VIGIL / "taxonomy" / "generated" / "VIGIL.FailureTaxonomy.CaseFileExamples.json"
TAXONOMY_INDEX = VIGIL / "taxonomy" / "VIGIL.FailureTaxonomy.Index.json"
REPOSITORY = "CAM-Initiative/Vigil"
BRANCH = "main"
NOTICE = (
    "Generated by vigil/scripts/build-vigil-public-records.py from canonical Incident "
    "records under vigil/records/incidents/; edit source records only."
)
GENERATED_PROVENANCE = {
    "content_origin": "deterministically-generated",
    "generation_mode": "deterministic-generation",
    "human_role": "contract-approver",
    "human_authorship": False,
    "human_review_status": "not-reviewed",
    "human_verification_status": "not-verified",
}
PRESERVE_EMPTY_KEYS = {
    "legacy_sources", "legacy_provenance", "secondary_classifications",
    "external_incident_references",
}


def load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected one JSON object")
    return value


def prune(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            key: cleaned
            for key, item in value.items()
            if (cleaned := prune(item)) not in (None, "", [], {}) or key in PRESERVE_EMPTY_KEYS
        }
    if isinstance(value, list):
        return [cleaned for item in value if (cleaned := prune(item)) not in (None, "", [], {})]
    return value


def write(path: Path, value: Any) -> None:
    path.write_text(
        json.dumps(prune(value), indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def relative(path: Path) -> str:
    return path.resolve().relative_to(ROOT.resolve()).as_posix()


def github_url(path: str) -> str:
    return f"https://github.com/{REPOSITORY}/blob/{BRANCH}/{path}"


def raw_url(path: str) -> str:
    return f"https://raw.githubusercontent.com/{REPOSITORY}/{BRANCH}/{path}"


def sources(record: dict[str, Any]) -> list[dict[str, Any]]:
    value = record.get("source_records")
    return [item for item in value if isinstance(item, dict)] if isinstance(value, list) else []


def text_terms(*values: Any) -> list[str]:
    """Return a compact, deterministic search vocabulary without embedding source objects."""
    terms: dict[str, str] = {}

    def collect(value: Any) -> None:
        if isinstance(value, str):
            cleaned = value.strip()
            if cleaned:
                terms.setdefault(cleaned.casefold(), cleaned)
        elif isinstance(value, list):
            for item in value:
                collect(item)

    for value in values:
        collect(value)
    return sorted(terms.values(), key=str.casefold)


def incident_search_terms(record: dict[str, Any]) -> list[str]:
    identity = record.get("record_identity") if isinstance(record.get("record_identity"), dict) else {}
    incident = record.get("incident_identity") if isinstance(record.get("incident_identity"), dict) else {}
    system = record.get("system_context") if isinstance(record.get("system_context"), dict) else {}
    jurisdiction = record.get("jurisdictional_context") if isinstance(record.get("jurisdictional_context"), dict) else {}
    taxonomy = record.get("taxonomy_classification") if isinstance(record.get("taxonomy_classification"), dict) else {}
    assessment = record.get("severity_assessment") if isinstance(record.get("severity_assessment"), dict) else {}
    primary = taxonomy.get("primary_classification") if isinstance(taxonomy.get("primary_classification"), dict) else {}
    secondary = taxonomy.get("secondary_classifications") if isinstance(taxonomy.get("secondary_classifications"), list) else []
    source_list = sources(record)

    return text_terms(
        incident.get("historical_event_name"),
        system.get("vendor_cluster"),
        system.get("primary_evidenced_vendors"),
        system.get("evidenced_vendors"),
        system.get("evidenced_products_or_services"),
        system.get("evidenced_models_or_runtimes"),
        system.get("product_or_service"),
        system.get("specific_model_or_runtime"),
        system.get("model_or_product"),
        system.get("system_type"),
        system.get("interface_surface"),
        jurisdiction.get("primary_jurisdiction"),
        jurisdiction.get("secondary_jurisdictions"),
        jurisdiction.get("sector"),
        jurisdiction.get("regulatory_surface"),
        taxonomy.get("taxonomy_version"),
        [
            value
            for item in secondary
            if isinstance(item, dict)
            for value in (item.get("class_id"), item.get("family_id"))
            if value
        ],
        assessment.get("assessment_status"),
        [
            value
            for item in source_list
            for value in (
                item.get("source_title"),
                item.get("author_or_publisher"),
                item.get("source_platform"),
                item.get("source_type"),
            )
            if value
        ],
    )


def incident_entry(path: Path, record: dict[str, Any]) -> dict[str, Any]:
    identity = record.get("record_identity") if isinstance(record.get("record_identity"), dict) else {}
    incident = record.get("incident_identity") if isinstance(record.get("incident_identity"), dict) else {}
    system = record.get("system_context") if isinstance(record.get("system_context"), dict) else {}
    taxonomy = record.get("taxonomy_classification") if isinstance(record.get("taxonomy_classification"), dict) else {}
    assessment = record.get("severity_assessment") if isinstance(record.get("severity_assessment"), dict) else {}
    primary = taxonomy.get("primary_classification") if isinstance(taxonomy.get("primary_classification"), dict) else {}
    if not primary:
        legacy_primary_class = taxonomy.get("primary_class")
        primary = legacy_primary_class if isinstance(legacy_primary_class, dict) else {}
    primary_family = taxonomy.get("primary_family") if isinstance(taxonomy.get("primary_family"), dict) else {}
    record_path = relative(path)

    return prune({
        "id": record.get("id"),
        "record_type": record.get("record_type"),
        "record_state": record.get("record_state"),
        "record_version": identity.get("version"),
        "record_last_updated": identity.get("updated"),
        "date_recorded": record.get("date_recorded"),
        "title": identity.get("title") or record.get("summary") or record.get("id"),
        "summary": record.get("summary"),
        "platform_or_vendor": system.get("platform_or_vendor"),
        "severity": assessment.get("severity"),
        "classification_status": taxonomy.get("classification_status"),
        "primary_class_id": primary.get("class_id"),
        "primary_family_id": primary.get("family_id") or primary_family.get("family_id"),
        "occurred_from": incident.get("occurred_from"),
        "search_terms": incident_search_terms(record),
        "path": record_path,
        "github_blob_url": github_url(record_path),
        "raw_url": raw_url(record_path),
    })


def taxonomy_examples(records: list[dict[str, Any]]) -> dict[str, Any]:
    taxonomy = load(TAXONOMY_INDEX)
    classes: dict[str, list[dict[str, Any]]] = {}
    for family in taxonomy.get("families", []):
        if not isinstance(family, dict) or not isinstance(family.get("file"), str):
            continue
        document = load(TAXONOMY_INDEX.parent / family["file"])
        for item in document.get("classes", []):
            if isinstance(item, dict) and isinstance(item.get("class_id"), str):
                classes[item["class_id"]] = []
    for record in records:
        block = record.get("taxonomy_classification")
        if not isinstance(block, dict):
            continue
        mappings: list[tuple[str, dict[str, Any]]] = []
        primary = block.get("primary_classification")
        if isinstance(primary, dict):
            mappings.append(("primary", primary))
        secondary = block.get("secondary_classifications")
        if isinstance(secondary, list):
            mappings.extend(("secondary", item) for item in secondary if isinstance(item, dict))
        for role, mapping in mappings:
            class_id = mapping.get("class_id")
            if class_id not in classes:
                continue
            classes[class_id].append(prune({
                "incident_id": record.get("id"),
                "incident_title": record.get("record_identity", {}).get("title"),
                "classification_role": role,
                "classification_basis": mapping.get("classification_basis"),
                "classification_confidence": mapping.get("classification_confidence"),
            }))
    return {
        "generated_notice": NOTICE, "generated_from": "vigil/records/incidents/",
        "authorship_provenance": {
            **GENERATED_PROVENANCE,
            "upstream_provenance": ["vigil/records/incidents/", relative(TAXONOMY_INDEX)],
        },
        "classes": classes,
    }


def build() -> None:
    paths = sorted(INCIDENTS.glob("VIGIL-INC-*.json"), key=lambda item: item.name)
    records = [load(path) for path in paths]
    entries = [incident_entry(path, record) for path, record in zip(paths, records)]
    provenance = {**GENERATED_PROVENANCE, "upstream_provenance": ["vigil/records/incidents/"]}
    incident_index = {
        "registry_type": "incidents", "generated_notice": NOTICE,
        "generated_from": "vigil/records/incidents/", "authorship_provenance": provenance,
        "record_count": len(entries), "records": entries,
    }
    index_path = relative(INCIDENT_INDEX)
    master = {
        "registry_type": "vigil_registry_master", "generated_notice": NOTICE,
        "generated_from": [index_path],
        "authorship_provenance": {**GENERATED_PROVENANCE, "upstream_provenance": [index_path]},
        "registry_count": 1, "record_count": {"incidents": len(entries), "total": len(entries)},
        "registries": {"incidents": {
            "path": index_path, "github_blob_url": github_url(index_path),
            "raw_url": raw_url(index_path), "record_count": len(entries),
        }},
    }
    write(INCIDENT_INDEX, incident_index)
    write(MASTER_INDEX, master)
    write(TAXONOMY_EXAMPLES, taxonomy_examples(records))
    print(
        f"Wrote lightweight Incident index for {len(entries)} canonical records "
        f"({INCIDENT_INDEX.stat().st_size} bytes) and registry manifest "
        f"({MASTER_INDEX.stat().st_size} bytes)."
    )


if __name__ == "__main__":
    build()
