#!/usr/bin/env python3
"""Build the generated VIGIL aggregate records file from individual records."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
VIGIL_DIR = ROOT / "vigil"
RECORDS_ROOT = VIGIL_DIR / "records"
RECORD_DIRS = [
    RECORDS_ROOT / "open",
    RECORDS_ROOT / "clusters",
    RECORDS_ROOT / "closed",
]
OUTPUT_PATH = VIGIL_DIR / "VIGIL.Records.json"


def record_files() -> list[Path]:
    files: list[Path] = []
    for directory in RECORD_DIRS:
        if directory.exists():
            files.extend(directory.glob("*.json"))
    return sorted(files, key=lambda path: path.as_posix())


def load_records() -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in record_files():
        with path.open("r", encoding="utf-8") as handle:
            record = json.load(handle)
        if not isinstance(record, dict):
            raise TypeError(f"{path} must contain one JSON object")
        records.append(record)
    return sorted(records, key=lambda record: record.get("id", ""))


def build() -> None:
    records = load_records()
    aggregate = {
        "generated_notice": "Generated by vigil/scripts/build-vigil-records.py; edit individual files under vigil/records/ instead.",
        "generated_from": "vigil/records/",
        "generated_at_utc": datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z"),
        "record_count": len(records),
        "records": records,
    }
    OUTPUT_PATH.write_text(
        json.dumps(aggregate, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT_PATH} with {len(records)} records.")


if __name__ == "__main__":
    build()
