#!/usr/bin/env python3
"""One-off EXTREQ-06 fidelity repair for IEEE 7000-2021; stores no IEEE text."""
import argparse,copy,hashlib,json
from pathlib import Path
from external_requirements_io import load_requirements_document,write_requirements_document
ROOT=Path(__file__).resolve().parents[1]; REQ=ROOT/'external_governance'/'requirements'
LEDGER=REQ/'metadata-review.json'; ASSURANCE=REQ/'source-review-assurance.json'; FIDELITY=REQ/'source-fidelity.json'
SID='EXT-31AD0314218F'; ESID='IEEE-7000'; VER='2021'; FP='95bc320d2635855ba0e366820a431f2d76e1f44a15664b82ee16b9ecc4139851'; DIG='559bdf6648f0d5f70529fd71848f068c92718ca9aa577a7de7abd8dc060b8ef6'; LOC='https://standards.ieee.org/ieee/7000/6781/'; DATE='2026-09-03'
TUPLE_DIGEST='e7e5fa25923b366a663ba14cd5256e1ee9aff8450243c12346f705b48464c1b2'
F=('applicable_actor','governed_object','timing_or_frequency','required_artefacts','evidence_expectation','verification_method','applicability_conditions','exceptions_or_qualifications')
NEW=[
('EXTREQ-9F9F312D1F384F0A','7.3(h)(3)','7000-conops-refined-as-ethics-develops','Refine the ConOps as information develops on prioritized values, ethical value requirements and ethical risk-based design characteristics.','EXTREQ-B29500CC6AF4EB3B'),
('EXTREQ-6B251B00C962BBBC','8.3(e)','7000-value-risks-opportunities-recorded','Identify and record potential technical and organizational risks and opportunities affecting the values.','EXTREQ-C3E5B151DB2EE358'),
('EXTREQ-AA32F6158A98B7E1','8.3(f)','7000-prioritized-value-clusters-refined','Refine prioritized value clusters through conceptual analysis, external value demonstrators, risk and opportunity treatment, and conflict annotation.','EXTREQ-C3E5B151DB2EE358'),
('EXTREQ-C4216CD9308BCAE5','8.3(g)','7000-prioritized-values-approved','Obtain approval for prioritized values and record the approved value clusters, decision, authority and rationale.','EXTREQ-C3E5B151DB2EE358')]
OBJ={'7':['system-of-interest concept of operations, use context, stakeholders, control and feasibility context'],'8':['stakeholder ethical values, value demonstrators, value clusters and value-prioritization decisions for the system of interest'],'9':['ethical value requirements and value-based system requirements for the system of interest'],'10':['ethical risk-based system design, value dispositions, control mechanisms and associated risks'],'11':['ethical information, transparency rules, stakeholder communications, Value Register and Case for Ethics']}
COND=['Applies during system conception and design where an organization is seeking to uncover, address and monitor value concerns for a system of interest intended for a discernible context.']
QUAL=['IEEE 7000-2021 is voluntary and does not by itself establish regulatory compliance or guarantee that the resulting system is ethical.']
ART={
'7.3(a)':['Representation of current and plausible system use contexts.'],'7.3(b)':['Identified stakeholder groups and stakeholder representatives.'],'7.3(c)':['Recorded controls needed to preserve ethical values in the concept.'],'7.3(e)':['Collected legal-boundary and social/environmental feasibility information, including initial value harms and benefits.'],'7.3(f)':['One or more represented system concepts of operation.'],'7.3(h)':['Recorded technical and organizational risks and improvements affecting the ConOps and the decision on further value analysis and risk assessment.'],'7.3(h)(3)':['Refined concept of operations.'],'8.3(a)':['Designated stakeholder group for ethical-values elicitation and prioritization.'],'8.3(b)(5)':['Value Register entries for core values, associated values, issues and value demonstrators.'],'8.3(c)':['Confirmed value clusters and descriptions recorded in the Value Register.'],'8.3(d)':['Value Register entries recording incompatibilities with external sources and conflicts affecting value prioritization.'],'8.3(e)':['Recorded technical and organizational risks and opportunities affecting the values.'],'8.3(f)':['Refined prioritized value clusters with added or excluded value demonstrators and annotated conflicts.'],'8.3(g)':['Value Register or preliminary Case for Ethics recording approved value clusters, decision, approving authority and rationale.'],'9.3(a)':['Ethical value requirements recorded with unique references, associated risks, prioritized core values, assumptions and constraints.'],'9.3(c)':['Value-based system requirements with unique references, traceability, risks, assumptions, constraints, measurement targets and acceptance criteria where applicable.'],'9.3(d)':['Adjusted ethical requirements and related updates recorded in the Case for Ethics and requirements register when needed.'],'9.3(e)':['Updated risk register and Value Register, with approval of value-based requirements recorded in the Case for Ethics.'],'10.3(c)':['Documented ethical value control analysis.'],'10.3(e)(3-7)':['Updated system design documentation and Case for Ethics recording final risk treatments, opportunity enhancements and validation results.'],'11.3(a)':['Recorded organizational transparency rules covering information availability, maintenance and approval.'],'11.3(c)':['Case for Ethics providing access to collected ethical information during development and afterward.']}
METH={
'7.3(c)':['Analyze technical and organizational control over the envisaged system and its relevant system-of-systems elements.'],'8.3(b)(1)':['Conduct benefits-and-harms value analysis for stakeholder impacts under scaled implementation.'],'8.3(b)(2)':['Conduct virtue-ethical analysis of potential effects on stakeholder character.'],'8.3(b)(3)':['Conduct duty-ethical analysis of stakeholder or project-team personal value maxims.'],'8.3(c)':['Conceptually analyze elicited values, form value clusters, verify that distinct values are not lost, and confirm the clusters with project stakeholders.'],'8.3(d)':['Prioritize core values using the stated ethical considerations, compare priorities with external sources, and identify conflicts affecting prioritization.'],'8.3(f)':['Perform conceptual value analysis and refine prioritized clusters using external demonstrators, risk/opportunity considerations and conflict annotation.'],'8.3(g)':['Review prioritized values and related risks/opportunities with top management and relevant stakeholders, repeating activities as needed to obtain acceptable value clusters.'],'9.3(b)':['Validate ethical value requirements with selected stakeholders, including top management and the project team.'],'9.3(d)':['Evaluate feasibility, harmonize requirements, analyze control implications, and adjust requirements using evaluation, risk analysis and design feedback.'],'10.3(b)':['Estimate likelihood and consequence, combine them to derive risk level, and prioritize the risk.'],'10.3(c)':['Analyze system elements and ownership, specify control mechanisms, and where feasible simulate or prototype functions to verify control effectiveness and acceptability with stakeholders.'],'10.3(e)(1-2)':['Verify traceability and fulfilment of value-based requirements through design dispositions and validate stakeholder tolerability of residual value risks.'],'10.3(e)(8)':['Use design verification and continued monitoring to determine when changing contexts, value priorities or technical needs require design modification and process reiteration.']}
TIME={'7.3(h)(3)':['As information develops regarding prioritized values, ethical value requirements and ethical risk-based design characteristics.'],'8.3(g)':['Repeat the relevant value activities as needed until acceptable value clusters can be approved.'],'10.3(e)(8)':['Through continued monitoring after design verification as contexts, value priorities or technical needs change.'],'11.2(a)':['During system development and afterward.'],'11.3(c)':['During system development and afterward.']}
def md(c):
 m={x:[] for x in F}; m['applicable_actor']=['organization responsible for the system of interest'] if c.startswith('11.') else ['project responsible for the system of interest']; m['governed_object']=OBJ[c.split('.',1)[0]]; m['applicability_conditions']=COND; m['exceptions_or_qualifications']=QUAL
 if '.2(' in c:m['evidence_expectation']=[f'Demonstrable evidence that the stated {c} process outcome has been achieved for the system of interest.']
 if c in ART:m['required_artefacts']=ART[c]
 if c in METH:m['verification_method']=METH[c]
 if c in TIME:m['timing_or_frequency']=TIME[c]
 if c.startswith('9.3'):m['timing_or_frequency']=['Incrementally and iteratively, in continuous interaction with general system development.']
 return m
def did(c,k):return 'EXTREQ-'+hashlib.sha256('|'.join((SID,VER,c,k)).encode()).hexdigest()[:16].upper()
def load(p):return json.loads(p.read_text())
def dump(p,v):p.write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
def run(write):
 d=load_requirements_document(); old=[r for r in d['requirements'] if r.get('vigil_source_id')==SID and r.get('source_version')==VER]
 if len(old)!=55:raise ValueError(f'expected 55 established records, found {len(old)}')
 tuples=sorted((r['requirement_id'],r['clause_or_control'],r['identity_key']) for r in old); td=hashlib.sha256(json.dumps(tuples,separators=(',',':')).encode()).hexdigest()
 if td!=TUPLE_DIGEST:raise ValueError('established IEEE 7000 identity tuples changed; refusing repair')
 by={r['requirement_id']:r for r in d['requirements']}; n=by['EXTREQ-C3E5B151DB2EE358']; s='Prioritize core values using the stated ethical considerations, compare value priorities with external sources, and record incompatibilities and conflicts affecting prioritization.'; n['requirement_summary']=s;n['governance_expectation']=s
 for rid,c,k,s,t in NEW:
  if did(c,k)!=rid or rid in by:raise ValueError(f'new identity conflict {rid}')
  r=copy.deepcopy(by[t]);r.update(requirement_id=rid,identity_key=k,clause_or_control=c,requirement_summary=s,governance_expectation=s,source_defined_tags=[{'scheme':'IEEE-7000-clause','values':[c]}]);[r.__setitem__(x,[]) for x in F];d['requirements'].append(r);by[rid]=r
 ids={r['requirement_id'] for r in old}|{x[0] for x in NEW}; rev=[by[x] for x in ids];pop={x:0 for x in F}
 for r in rev:
  x=md(r['clause_or_control'])
  for f in F:r[f]=x[f];pop[f]+=bool(x[f])
  r['source_review_date']=DATE;p=r['interpretation_provenance']
  if p.get('source_metadata_fingerprint')!=FP:raise ValueError(f'fingerprint changed {r["requirement_id"]}')
  p.update(reviewed_source_digest=DIG,reviewed_source_digest_algorithm='sha256',reviewed_source_digest_status='recorded')
 d['requirements'].sort(key=lambda r:r['requirement_id']);d['requirement_count']=len(d['requirements']);d['updated_at']=DATE
 l=load(LEDGER);lb={e['requirement_id']:e for e in l['entries']}
 for r in rev:
  x=md(r['clause_or_control']);notes=['Reviewed directly against the lawfully accessed licensed IEEE 7000-2021 primary text.','Metadata was populated only where supported by the source; source silence is recorded explicitly.']
  if r['requirement_id']=='EXTREQ-C3E5B151DB2EE358':notes.append('Established identity retained; the analytical summary was narrowed to Clause 8.3(d), while source-explicit approval is represented separately at Clause 8.3(g).')
  if r['requirement_id'] in {x[0] for x in NEW}:notes.append('Deterministic requirement added for a normative activity omitted from the prior bounded extraction.')
  lb[r['requirement_id']]={'requirement_id':r['requirement_id'],'reviewed_at':DATE,'review_basis':'licensed-primary-text','review_notes':notes,'field_status':{f:'populated-reviewed' if x[f] else 'not-specified-by-source' for f in F}}
 l['updated_at']=DATE;l['entries']=sorted(lb.values(),key=lambda e:e['requirement_id'])
 a=load(ASSURANCE);sr=[e for e in a['source_reviews'] if not(e.get('vigil_source_id')==SID and e.get('source_version')==VER)];sr.append({'vigil_source_id':SID,'external_source_id':ESID,'source_version':VER,'source_metadata_fingerprint':FP,'reviewed_source_digest':{'algorithm':'sha256','digest':DIG,'recorded_at':DATE,'artefact_role':'reviewed-primary-source','access_basis':'licensed-primary','evidence_ref':LOC},'assurance_provenance':[]});a['updated_at']=DATE;a['source_reviews']=sorted(sr,key=lambda e:(e['external_source_id'],e['source_version']))
 fi=load(FIDELITY);fe=[e for e in fi['entries'] if not(e.get('vigil_source_id')==SID and e.get('source_version')==VER)];fe.append({'vigil_source_id':SID,'external_source_id':ESID,'source_version':VER,'fidelity_status':'assured','effective_extraction_status':'complete','assessment_basis':'Direct clause-level comparison against the complete lawfully accessed IEEE 7000-2021 licensed primary PDF confirmed all 55 established identities as defensible but identified four omitted normative activities: ConOps refinement at 7.3(h)(3) and value-risk, refinement and approval activities at 8.3(e-g). All 55 established IDs and clause locators were preserved; the over-broad 8.3(d) analytical summary was narrowed without changing identity; four deterministic records were added. The repaired 59-record representation preserves source-supported metadata across the reviewed fidelity dimensions and explicitly records source silence.','known_fidelity_gaps':[],'audited_requirement_ids':sorted(ids),'next_action':'Retain the 59 reviewed identities and repeat the fidelity review on material revision of IEEE 7000.'});fi['reviewed_at']=DATE;fi['entries']=sorted(fe,key=lambda e:(e['external_source_id'],e['source_version']))
 print('IEEE 7000 repair valid: 55 established IDs preserved; 4 deterministic activities added; 59 reviewed records');print(json.dumps(pop,sort_keys=True));print(DIG)
 if write:write_requirements_document(d);dump(LEDGER,l);dump(ASSURANCE,a);dump(FIDELITY,fi)
 return 0
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');raise SystemExit(run(p.parse_args().write))
